### ISSUE TITLE
Units integrated intensity plot

### ISSUE THREAD

**Issue by jacoterh** [LHCfitNikhef/CBL-ML#1]
Hi Isabel,

I am opening this issue to ask you about the units that you pass to the integrated intensity plots axes. At

https://github.com/LHCfitNikhef/CBL-ML/blob/1beefda7512efe8fddb69e4611afeaecfb69f344/EELS_KK/pyfiles/bash_train_pyfiles/image_class_bs.py#L1623

you seem to be giving [m], but that should be [nm] right?

**Comment by jacoterh** [comment]
I also noticed that the origin of the integrated intensity plots is at the top-left, is there any specific reason why you made this choice? Why not use the bottom-left?

**Comment by isabelpostmes** [comment]
Hi Jaco,

It should be micron, this is a glitch that arrises from the fact that I
initially set everything to SI units, but than we wanted the axis in micron
rather than meter. I'll fix it more robustly, but for now you can just
replace m with micron if you want. The counting that starts in the left
upper corner is default in the 2D plots of matplotlib, thats why. I assumed
it to be standard practice. Is it not? It should be switchable I presume.

Also very fancy opening an issue!! What should I do to close it or fix it
or something?



Op do 27 mei 2021 om 10:30 schreef jacoterh ***@***.***>:

**Comment by jacoterh** [comment]
Thanks Isabel, I have changed it to microns. You can use LaTeX formatting to write \mu m. 
<img width="549" alt="image" src="https://user-images.githubusercontent.com/54140851/119809548-84d0d980-bee5-11eb-873d-ccbb6e26cd76.png">. 

The counting is fine this way, but in the future it might be more convenient to let the origin start in the bottom-left. 

To close an issue you should first open the issue on GitHub itself and then you'll see a button down below that lets you close it.

**Comment by jacoterh** [comment]
Another thing I wanted to ask you about is how to change the significance of the axis ticks. I noticed you included an option sig for this in the code, but it does not affect the plot, or am I missing something?

https://github.com/LHCfitNikhef/CBL-ML/blob/1beefda7512efe8fddb69e4611afeaecfb69f344/EELS_KK/pyfiles/bash_train_pyfiles/image_class_bs.py#L1625

**Comment by isabelpostmes** [comment]
The problem at this point is the fact that I haven't used plot_sum in a
while, but only used plot_heatmap, where you can input the data you want to
plot yourself. I noted to myself that I should change plot_sum to just call
on plot_heatmap, but haven't done so yet. All these things should already
be incorporated in plot_heatmap.

Op do 27 mei 2021 om 12:23 schreef jacoterh ***@***.***>:
